apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  containers:
    - resources:
        limits:
          cpu: 0.5
      image: mongo:3.2.4
      name: mongo
      ports:
        - containerPort: 27017
          name: mongo
